apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql-server
      tier: db
  template:
    metadata:
      labels:
        app: mysql-server
        tier: db
    spec:
      containers:
        - name: mysql-server
          image: mysql:5.7
          args:
            - "--ignore-db-dir=lost+found"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
